import React from 'react';
import { Scale, CheckCircle2, RotateCcw, ShieldCheck } from 'lucide-react';

const PredictionResult = ({ result, onReset }) => {
  if (!result) return null;

  return (
    <div className="card result-card animate-fade-in">
      <div className="card-header border-b">
        <div className="icon-badge bg-emerald-500/20 text-emerald-400">
          <Scale className="icon-md" />
        </div>
        <div>
          <h2>Prediction Result</h2>
          <p className="card-subtitle">Generated by Trained ML Model</p>
        </div>
      </div>

      <div className="result-body">
        <div className="result-grid">
          <div className="result-item">
            <span className="result-label">Input Height</span>
            <div className="result-value-secondary">
              {result.height} <span className="unit">cm</span>
            </div>
          </div>

          <div className="result-item highlight-item">
            <span className="result-label font-semibold text-emerald-400">Predicted Weight</span>
            <div className="result-value-primary">
              {result.predicted_weight} <span className="unit-large">kg</span>
            </div>
          </div>
        </div>

        <div className="notice-box">
          <ShieldCheck className="icon-sm text-cyan-400 shrink-0" />
          <span>Prediction generated by your trained Machine Learning model.</span>
        </div>

        <button
          type="button"
          onClick={onReset}
          className="reset-btn"
        >
          <RotateCcw className="icon-sm" />
          <span>Predict Another Height</span>
        </button>
      </div>
    </div>
  );
};

export default PredictionResult;
